# Atlas VPN - windows
[Interface]
PrivateKey = MENuCYL3ItprQQgBHhp1ZqMHFddfkdwyajSI+XzEr1E=
Address = 10.77.0.4/32, fd42:6174:6c61:7300::4/128
DNS = 1.1.1.1, 1.0.0.1
MTU = 1380

[Peer]
PublicKey = cnfsBZuJ/neFg840niOih4qy8qAFPZWAuNZ1/q1ZJh8=
PresharedKey = qPXcuVR8zECQ3BBHGOg48Dk7M166mXu2qlompX4nr9Y=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 208.167.248.147:51820
PersistentKeepalive = 25
