# Atlas VPN - mac
[Interface]
PrivateKey = mNvd2lshsCaqSzC0siaLPsJ3T39HJo8d407P09a/alI=
Address = 10.77.0.3/32, fd42:6174:6c61:7300::3/128
DNS = 1.1.1.1, 1.0.0.1
MTU = 1380

[Peer]
PublicKey = cnfsBZuJ/neFg840niOih4qy8qAFPZWAuNZ1/q1ZJh8=
PresharedKey = CMIO3Yu/xbzeF7hlp+SE9okQaMzkX/M06xZGRH8er0c=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 208.167.248.147:51820
PersistentKeepalive = 25
