# Atlas VPN - iphone
[Interface]
PrivateKey = +AhxlhnNr9IeWI3Wcrz8dE1DVpjoa70I+N35KWNJdE0=
Address = 10.77.0.2/32, fd42:6174:6c61:7300::2/128
DNS = 1.1.1.1, 1.0.0.1
MTU = 1380

[Peer]
PublicKey = cnfsBZuJ/neFg840niOih4qy8qAFPZWAuNZ1/q1ZJh8=
PresharedKey = SBlYOTDMIgRgWJFDlHBjtVsmhUURSXJQiCKxrYbY3aI=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 208.167.248.147:51820
PersistentKeepalive = 25
